Added pivotal tracker support to feature start

diff --git a/git-flow-feature b/git-flow-feature
--- a/git-flow-feature
+++ b/git-flow-feature
@@ -43,7 +43,7 @@ PREFIX=$(git config --get gitflow.prefix.feature)
 
 usage() {
 	echo "usage: git flow feature [list] [-v]"
-	echo "       git flow feature start [-F] <name> [<base>]"
+	echo "       git flow feature start [-FP] <name> [<base>]"
 	echo "       git flow feature finish [-rFk] <name|nameprefix>"
 	echo "       git flow feature publish <name>"
 	echo "       git flow feature track <name>"
@@ -184,6 +184,39 @@ parse_args() {
 	BRANCH=$PREFIX$NAME
 }
 
+parse_base_name () {
+	parse_cmdline "$@"
+
+	if [ $# -eq 1 ]; then
+		if [[ $1 == "-P" ]]; then
+			NAME=""
+			BRANCH=$NAME
+			BASE=$DEVELOP_BRANCH
+		else
+			NAME=$1
+			BRANCH=$PREFIX$NAME
+			BASE=$DEVELOP_BRANCH
+		fi
+	fi
+	if [ $# -eq 2 ]; then
+		if [[ $1 == "-F" || $1 == "-P" ]]; then
+			NAME=$2
+			BRANCH=$PREFIX$NAME
+			BASE=$DEVELOP_BRANCH
+		else
+			NAME=$1
+			BRANCH=$PREFIX$NAME
+			BASE=$2
+		fi
+	fi
+	if [ $# -eq 3 ]; then
+		NAME=$2
+		BRANCH=$PREFIX$NAME
+		BASE=$3
+	fi
+}
+
+
 parse_remote_name() {
 	parse_cmdline "$@"
 
@@ -195,12 +228,62 @@ parse_remote_name() {
 
 cmd_start() {
 	DEFINE_boolean fetch false 'fetch from origin before performing local operation' F
-	parse_args "$@"
-	BASE=${2:-$DEVELOP_BRANCH}
-	require_name_arg
+	DEFINE_boolean pivotal false 'pull feature from Pivotal Tracker and update status to started' P
+	parse_base_name "$@"
+
+	if ! flag pivotal; then
+		require_name_arg
+	fi
 
 	# sanity checks
 	require_branch_absent "$BRANCH"
+
+	STORY_ID=""
+	PIVOTAL_API_KEY=""
+	PIVOTAL_PROJECT_ID=""
+
+	if flag pivotal; then
+		if ! gitflow_has_pivotal_configured; then
+			die "Pivotal Tracker is not configued"
+		fi
+
+		PIVOTAL_PROJECT_ID=$(git config --get pivotal.project-id)
+		PIVOTAL_API_KEY=$(git config --get pivotal.api-token)
+		
+		# Pull our next story id
+		# TODO: Allow us to pass a story id or an owner name/initials
+		STORY_ID=$(curl -o - -sS -H "X-TrackerToken: $PIVOTAL_API_KEY" -X GET "https://www.pivotaltracker.com/services/v3/projects/$PIVOTAL_PROJECT_ID/stories?filter=type%3Afeature%20current_state%3Aunstarted&limit=1" | grep "<id type=\"integer\">" | cut -d \> -f2 | cut -d\< -f1)
+		if [ "$STORY_ID" == "" ]; then
+			# If no story is found, ask whether they want to continue on without
+			default_suggestion="N"
+			printf "Could not find an unstarted story to use. Continue without? (Y/N)? [$default_suggestion] "
+			read answer
+			[ "$answer" = "-" ] && prefix= || prefix=${answer:-$default_suggestion}
+			if [[ "$prefix" != "Y" && "$prefix" != "y" ]]; then
+				die "Exiting..."
+			fi
+		else
+			# Grab the story name -- make sure it's what they want
+			# TODO: Change this to query the story id we have in scope already
+			STORY_NAME=$(curl -o - -sS -H "X-TrackerToken: $PIVOTAL_API_KEY" -X GET "https://www.pivotaltracker.com/services/v3/projects/$PIVOTAL_PROJECT_ID/stories?filter=type%3Afeature%20current_state%3Aunstarted&limit=1" | grep "<name>" | cut -d \> -f2 | cut -d\< -f1)
+			default_suggestion="Y"
+			printf "Use story #$STORY_ID '$STORY_NAME' (Y/N)? [$default_suggestion] "
+			read answer
+			[ "$answer" = "-" ] && prefix= || prefix=${answer:-$default_suggestion}
+			if [[ "$prefix" == "Y" || "$prefix" == "y" ]]; then
+				# If no branch was given in the command line, then munge one together
+				# Otherwise, just append on our story id
+				if [[ "$BRANCH" == "" ]]; then
+					BRANCH=$(clean_branch_name "$STORY_NAME")
+					BRANCH="feature/$BRANCH-$STORY_ID"
+				else
+					BRANCH="$BRANCH-$STORY_ID"
+				fi
+			else	
+				die "Exiting..."
+			fi
+		fi
+	fi
 
 	# update the local repo with remote changes, if asked
 	if flag fetch; then
@@ -214,13 +297,23 @@ cmd_start() {
 	fi
 
 	# create branch
+	echo "git checkout -b $BRANCH $BASE"
 	if ! git checkout -b "$BRANCH" "$BASE"; then
 		die "Could not create feature branch '$BRANCH'"
+	fi
+
+	# If we have a valid story id and we've gotten this far, then mark
+	# the story as started
+	if [ "$STORY_ID" != "" ]; then
+		ret=$(curl -o - -sS -H "X-TrackerToken: $PIVOTAL_API_KEY" -X PUT -H "Content-type: application/xml" -d "<story><current_state>started</current_state></story>" "https://www.pivotaltracker.com/services/v3/projects/$PIVOTAL_PROJECT_ID/stories/$STORY_ID")
 	fi
 
 	echo
 	echo "Summary of actions:"
 	echo "- A new branch '$BRANCH' was created, based on '$BASE'"
+	if [ "$STORY_ID" != "" ]; then
+		echo "- Story #$STORY_ID was marked as started in Pivotal Tracker"
+	fi
 	echo "- You are now on branch '$BRANCH'"
 	echo ""
 	echo "Now, start committing on your feature. When done, use:"
